### ISSUE TITLE
Question: Removal of users & groups

### ISSUE THREAD

**Issue by baatch** [alexandruanghel/azdo-databricks#1]
Hello @alexandruanghel,

Just found your super awesome Repo :) !

Looking at the syncing of Users and groups shell scripts. 

Am I right in assuming that the scripts do not remove any users and groups and do you have any plans to include this functionality?

**Comment by alexandruanghel** [comment]
Hi @baatch sorry about the late reply.

You're correct about the scripts, they're fairly basic and not designed for a full fledged production solution, just to show how the APIs work.
You should use the official [enterprise app](https://docs.microsoft.com/en-us/azure/databricks/administration-guide/users-groups/scim/aad) or the [Terraform modules in this repo](https://github.com/alexandruanghel/azdo-databricks/tree/master/terraform/modules/databricks/azure-groups-sync) due to how it keeps track of the syncted users and groups in its state (and so it can decide to remove a user if it's not present in any groups - something more difficult with a script).

That being said, the `sync_group.sh` script uses a `PUT` which replaces the group membership every time, which means if a user is removed from a group in AD, that user should be removed from that group in Databricks as well.
And while users might not be removed, users without any group would not have by default much access in the first place.
